name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: web3-mises node ${{ matrix.node-version }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Test
        run: |
          yarn
          yarn build
        env:
          CI: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy files to S3
        run: |
          aws s3 cp --recursive \
           --region us-east-1 \
           build/ s3://web3.mises/main
      - name: Put object index.html to S3
        run: |
          aws s3api put-object --bucket web3.mises \
           --key main/index.html \
           --body build/index.html \
           --cache-control max-age=86400 \
           --content-type text/html
      - name: Invalidate cloudfront
        run: |
          aws cloudfront create-invalidation \
           --region us-east-1 \
           --distribution-id EGYSW0PD9IFEY \
           --paths "/index.html"
